org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

# Mod Properties
mod_id=enhancedtooltips
mod_name=EnhancedTooltips
mod_license=MIT
mod_authors=UltimatChamp, yanggx98
mod_description=A mod that overhauls tooltips, and adds some extra information.
mod_version=1.10.0
maven_group=dev.ultimatchamp

# Providers
modrinthId=8H6RXl2q
curseforgeId=1173737

# Minecraft Properties
deps.minecraft_version=[VERSIONED]
deps.mc_range=[VERSIONED]

# Fabric Properties
loader_version=0.19.5

# NeoForge Properties
deps.neoforge=[VERSIONED]

# Dependencies
deps.jankson_version=1.2.3
deps.yacl_version=[VERSIONED]
